'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'hi' | 'mr' | 'ta' | 'te' | 'gu' | 'bn';

export interface Language {
  code: LanguageCode;
  name: string;
  nativeName: string;
}

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    app_title: 'CrowdCivic AI',
    app_subtitle: 'AI Verification & Municipal Resolution System',
    citizen_portal: 'Citizen Portal',
    authority_portal: 'Municipal Authority Portal',
    admin_portal: 'Command Center & Audit',
    welcome: 'Welcome',
    report_issue: 'Report Issue',
    my_issues: 'My Reports',
    public_feed: 'Public Feed',
    leaderboard: 'Leaderboard',
    ai_agent: 'AI Civic Assistant',
    audit_logs: 'Audit Logs',
    analytics: 'Analytics',
    logout: 'Logout',
    signOut: 'Sign Out',
    sign_in: 'Sign In',
    sign_up: 'Create Account',
    status_pending: 'Pending Verification',
    status_verified: 'AI Verified',
    status_in_progress: 'In Progress',
    status_resolved: 'Resolved',
    status_rejected: 'Rejected',
    severity_high: 'High Severity',
    severity_medium: 'Medium Severity',
    severity_low: 'Low Severity',
    category_roads: 'Roads & Infrastructure',
    category_sanitation: 'Sanitation & Waste',
    category_water: 'Water Supply',
    category_electricity: 'Electricity & Lighting',
    category_other: 'Other Municipal Issue',
    submit: 'Submit Report',
    cancel: 'Cancel',
    search_placeholder: 'Search civic issues...',
    location: 'Location',
    upvote: 'Upvote',
    verify_resolution: 'Verify Resolution',
    verify_ai_photo: 'Verify with Live AI Photo',
    confidence_score: 'AI Confidence Score',
    view_details: 'View Details',
    export_data: 'Export Data',
    total_issues: 'Total Issues Reported',
    resolved_issues: 'Successfully Resolved',
    ai_verified_pct: 'AI Verification Rate',
    avg_resolution_time: 'Avg Resolution Time',
    incidents_command: 'Incidents & Resolution Command',
    authority_subtitle: 'Inspect citizen reports and resolve issues with mandatory 30-second live camera video proof & AI spatial verification.',
    refresh_incidents: 'Refresh Incidents',
    total_reports: 'Total Reports',
    pending_review: 'Pending Review',
    ai_resolved: 'AI Resolved',
    audit_failed: 'Audit Failed',
    search_authority_placeholder: 'Search Ticket ID, title, landmark...',
    inspect_resolve: 'Inspect & Resolve',
    record_live_video: 'Record 30s Live Video',
    recording_video: 'Recording Live Video...',
    submit_ai_verification: 'Submit for AI Verification',
    verifying_resolution: 'AI Spatial Verification in Progress...',
    verification_passed: 'Resolution Verified & Approved by AI',
    verification_failed: 'AI Resolution Audit Failed',
    citizen_complaint_details: 'Citizen Complaint Details',
    ticket_id: 'Ticket ID',
    category: 'Category',
    issue_type: 'Issue Type',
    severity: 'Severity',
    department: 'Department',
    reported_by: 'Reported By',
    location_address: 'Location / Address',
    community_votes: 'Community Verification Votes',
    admin_title: 'Municipal System Command Center',
    admin_subtitle: 'Full system monitoring, security audit logs, user role management, and dispute governance.',
    tab_audit: 'Security Audit Logs',
    tab_users: 'Registered Users & Roles',
    tab_config: 'System Security & PIN Config',
    tab_issues: 'Disputed Reports Governance',
    total_audit_events: 'Total Audit Events',
    denied_access_attempts: 'Denied Access Attempts',
    registered_users_count: 'Registered Users',
    disputed_reports_count: 'Disputed Reports',
    search_logs_placeholder: 'Search audit logs, user email, details...',
    filter_all: 'All Logs',
    filter_denied: 'Denied / Intercepted',
    filter_pin: 'PIN Activity',
    filter_login: 'Login / Auth',
    event_timestamp: 'Timestamp',
    action_event: 'Action Event',
    user_email: 'User Email',
    portal_accessed: 'Portal',
    status_outcome: 'Status / Outcome',
    details_summary: 'Details Summary',
    change_role: 'Change Role',
    role_citizen: 'Citizen',
    role_authority: 'Municipal Authority',
    role_admin: 'System Admin',
    update_pin: 'Update Security PIN',
    authority_pin: 'Municipal Authority Security PIN',
    admin_pin: 'System Admin Security PIN',
    save_pin: 'Save New PIN',
    pin_saved_success: 'PIN updated successfully',
    ai_verification_enabled: 'AI Resolution Verification Enabled',
  },
  hi: {
    app_title: 'क्राउडसिविक एआई',
    app_subtitle: 'एआई सत्यापन और नगर निगम समाधान प्रणाली',
    citizen_portal: 'नागरिक पोर्टल',
    authority_portal: 'नगर निगम प्राधिकरण पोर्टल',
    admin_portal: 'कमांड सेंटर और ऑडिट',
    welcome: 'स्वागत है',
    report_issue: 'समस्या दर्ज करें',
    my_issues: 'मेरी रिपोर्ट',
    public_feed: 'सार्वजनिक फ़ीड',
    leaderboard: 'लीडरबोर्ड',
    ai_agent: 'एआई नागरिक सहायक',
    audit_logs: 'ऑडिट लॉग',
    analytics: 'विश्लेषण',
    logout: 'लॉग आउट',
    signOut: 'साइन आउट',
    sign_in: 'साइन इन करें',
    sign_up: 'खाता बनाएं',
    status_pending: 'सत्यापन लंबित',
    status_verified: 'एआई सत्यापित',
    status_in_progress: 'प्रगति में',
    status_resolved: 'हल किया गया',
    status_rejected: 'अस्वीकृत',
    severity_high: 'उच्च गंभीरता',
    severity_medium: 'मध्यम गंभीरता',
    severity_low: 'कम गंभीरता',
    category_roads: 'सड़कें और बुनियादी ढांचा',
    category_sanitation: 'स्वच्छता और कचरा',
    category_water: 'जल आपूर्ति',
    category_electricity: 'बिजली और रोशनी',
    category_other: 'अन्य नगर समस्या',
    submit: 'रिपोर्ट जमा करें',
    cancel: 'रद्द करें',
    search_placeholder: 'नागरिक समस्याओं की खोज करें...',
    location: 'स्थान',
    upvote: 'समर्थन दें',
    verify_resolution: 'समाधान का सत्यापन करें',
    verify_ai_photo: 'लाइव एआई फोटो से सत्यापित करें',
    confidence_score: 'एआई विश्वास स्कोर',
    view_details: 'विवरण देखें',
    export_data: 'डेटा निर्यात करें',
    total_issues: 'कुल दर्ज मामले',
    resolved_issues: 'सफलतापूर्वक हल',
    ai_verified_pct: 'एआई सत्यापन दर',
    avg_resolution_time: 'औसत समाधान समय',
    incidents_command: 'घटना एवं समाधान कमान',
    authority_subtitle: 'नागरिक रिपोर्टों की जांच करें और 30-सेकंड लाइव कैमरा वीडियो प्रमाण और एआई स्थानिक सत्यापन के साथ समस्याओं का समाधान करें।',
    refresh_incidents: 'घटनाएं ताज़ा करें',
    total_reports: 'कुल रिपोर्ट',
    pending_review: 'समीक्षा लंबित',
    ai_resolved: 'एआई द्वारा हल',
    audit_failed: 'ऑडिट विफल',
    search_authority_placeholder: 'टिकट आईडी, शीर्षक, स्थान खोजें...',
    inspect_resolve: 'निरीक्षण एवं समाधान',
    record_live_video: '30 से० लाइव वीडियो रिकॉर्ड करें',
    recording_video: 'लाइव वीडियो रिकॉर्ड हो रहा है...',
    submit_ai_verification: 'एआई सत्यापन के लिए जमा करें',
    verifying_resolution: 'एआई स्थानिक सत्यापन जारी है...',
    verification_passed: 'समाधान सत्यापित एवं स्वीकृत',
    verification_failed: 'एआई समाधान ऑडिट विफल',
    citizen_complaint_details: 'नागरिक शिकायत विवरण',
    ticket_id: 'टिकट आईडी',
    category: 'श्रेणी',
    issue_type: 'समस्या का प्रकार',
    severity: 'गंभीरता',
    department: 'विभाग',
    reported_by: 'रिपोर्टकर्ता',
    location_address: 'स्थान / पता',
    community_votes: 'समुदाय सत्यापन वोट',
    admin_title: 'नगर निगम प्रणाली कमांड सेंटर',
    admin_subtitle: 'पूर्ण प्रणाली निगरानी, सुरक्षा ऑडिट लॉग, उपयोगकर्ता भूमिका प्रबंधन और विवाद शासन।',
    tab_audit: 'सुरक्षा ऑडिट लॉग',
    tab_users: 'पंजीकृत उपयोगकर्ता एवं भूमिकाएँ',
    tab_config: 'प्रणाली सुरक्षा एवं पिन कॉन्फिगरेशन',
    tab_issues: 'विवादित रिपोर्ट शासन',
    total_audit_events: 'कुल ऑडिट कार्यक्रम',
    denied_access_attempts: 'अस्वीकृत पहुँच प्रयास',
    registered_users_count: 'पंजीकृत उपयोगकर्ता',
    disputed_reports_count: 'विवादित रिपोर्ट',
    search_logs_placeholder: 'ऑडिट लॉग, ईमेल, विवरण खोजें...',
    filter_all: 'सभी लॉग',
    filter_denied: 'अस्वीकृत / इंटरसेप्टेड',
    filter_pin: 'पिन गतिविधि',
    filter_login: 'लॉगिन / ऑथ',
    event_timestamp: 'समय मोहर',
    action_event: 'कार्रवाई का प्रकार',
    user_email: 'उपयोगकर्ता ईमेल',
    portal_accessed: 'पोर्टल',
    status_outcome: 'स्थिति / परिणाम',
    details_summary: 'विवरण सारांश',
    change_role: 'भूमिका बदलें',
    role_citizen: 'नागरिक',
    role_authority: 'नगर निगम प्राधिकरण',
    role_admin: 'सिस्टम व्यवस्थापक',
    update_pin: 'सुरक्षा पिन अपडेट करें',
    authority_pin: 'नगर निगम प्राधिकरण सुरक्षा पिन',
    admin_pin: 'सिस्टम व्यवस्थापक सुरक्षा पिन',
    save_pin: 'नया पिन सहेजें',
    pin_saved_success: 'पिन सफलतापूर्वक अपडेट किया गया',
    ai_verification_enabled: 'एआई समाधान सत्यापन सक्रिय',
  },
  mr: {
    app_title: 'क्राउडसिव्हिक एआय',
    app_subtitle: 'एआय पडताळणी आणि महानगरपालिका निवारण प्रणाली',
    citizen_portal: 'नागरिक पोर्टल',
    authority_portal: 'महानगरपालिका अधिकारी पोर्टल',
    admin_portal: 'कमांड सेंटर आणि ऑडिट',
    welcome: 'सुस्वागतम',
    report_issue: 'तक्रार नोंदवा',
    my_issues: 'माझ्या तक्रारी',
    public_feed: 'सार्वजनिक फीड',
    leaderboard: 'लीडरबोर्ड',
    ai_agent: 'एआय नागरिक सहाय्यक',
    audit_logs: 'ऑडिट लॉग',
    analytics: 'विश्लेषण',
    logout: 'लॉग आउट',
    signOut: 'साइन आउट',
    sign_in: 'साइन इन करा',
    sign_up: 'खाते तयार करा',
    status_pending: 'पडताळणी प्रलंबित',
    status_verified: 'एआय पडताळलेले',
    status_in_progress: 'प्रगतीपथावर',
    status_resolved: 'सोडवले',
    status_rejected: 'नाकारले',
    severity_high: 'उच्च तीव्रतेचे',
    severity_medium: 'मध्यम तीव्रतेचे',
    severity_low: 'कमी तीव्रतेचे',
    category_roads: 'रस्ते आणि पायाभूत सुविधा',
    category_sanitation: 'स्वच्छता आणि कचरा',
    category_water: 'पाणी पुरवठा',
    category_electricity: 'वीज आणि दिवे',
    category_other: 'इतर नागरी समस्या',
    submit: 'तक्रार सबमिट करा',
    cancel: 'रद्द करा',
    search_placeholder: 'नागरी समस्या शोधा...',
    location: 'स्थान',
    upvote: 'समर्थन द्या',
    verify_resolution: 'निवारणाची पडताळणी करा',
    verify_ai_photo: 'थेट एआय फोटोने पडताळा',
    confidence_score: 'एआय विश्वासार्हता स्कोअर',
    view_details: 'तपशील पहा',
    export_data: 'डेटा निर्यात करा',
    total_issues: 'एकूण नोंदवलेल्या तक्रारी',
    resolved_issues: 'यशस्वीपणे निवारण',
    ai_verified_pct: 'एआय पडताळणी दर',
    avg_resolution_time: 'सरासरी निवारण वेळ',
    incidents_command: 'घटना आणि निवारण कमांड',
    authority_subtitle: 'नागरिक अहवालांची पाहणी करा आणि ३०-सेकंद थेट व्हिडिओ पुरावा आणि एआय स्थानिक पडताळणीसह समस्यांचे निवारण करा.',
    refresh_incidents: 'घटना रिफ्रेश करा',
    total_reports: 'एकूण अहवाल',
    pending_review: 'पुनरावलोकन प्रलंबित',
    ai_resolved: 'एआय द्वारे निवारित',
    audit_failed: 'ऑडिट अयशस्वी',
    search_authority_placeholder: 'तिकीट आयडी, शीर्षक, स्थान शोधा...',
    inspect_resolve: 'पाहणी आणि निवारण',
    record_live_video: '३० सेकंद थेट व्हिडिओ रेकॉर्ड करा',
    recording_video: 'थेट व्हिडिओ रेकॉर्ड होत आहे...',
    submit_ai_verification: 'एआय पडताळणीसाठी सबमिट करा',
    verifying_resolution: 'एआय स्थानिक पडताळणी सुरू आहे...',
    verification_passed: 'निवारण पडताळले आणि मंजूर',
    verification_failed: 'एआय निवारण ऑडिट अयशस्वी',
    citizen_complaint_details: 'नागरिक तक्रार तपशील',
    ticket_id: 'तिकीट आयडी',
    category: 'वर्ग',
    issue_type: 'समस्येचा प्रकार',
    severity: 'तीव्रता',
    department: 'विभाग',
    reported_by: 'तक्रारदार',
    location_address: 'स्थान / पत्ता',
    community_votes: 'समुदाय पडताळणी मते',
    admin_title: 'महानगरपालिका प्रणाली कमांड सेंटर',
    admin_subtitle: 'पूर्ण प्रणाली देखरेख, सुरक्षा ऑडिट लॉग, वापरकर्ता भूमिका व्यवस्थापन आणि विवाद शासन.',
    tab_audit: 'सुरक्षा ऑडिट लॉग',
    tab_users: 'नोंदणीकृत वापरकर्ते आणि भूमिका',
    tab_config: 'प्रणाली सुरक्षा आणि पिन कॉन्फिगरेशन',
    tab_issues: 'विवादित अहवाल शासन',
    total_audit_events: 'एकूण ऑडिट कार्यक्रम',
    denied_access_attempts: 'नाकारलेले प्रवेश प्रयत्न',
    registered_users_count: 'नोंदणीकृत वापरकर्ते',
    disputed_reports_count: 'विवादित अहवाल',
    search_logs_placeholder: 'ऑडिट लॉग, ईमेल, तपशील शोधा...',
    filter_all: 'सर्व लॉग',
    filter_denied: 'नाकारलेले / इंटरसेप्ट केलेले',
    filter_pin: 'पिन क्रियाकलाप',
    filter_login: 'लॉगिन / ऑथ',
    event_timestamp: 'वेळ',
    action_event: 'कारवाईचा प्रकार',
    user_email: 'वापरकर्ता ईमेल',
    portal_accessed: 'पोर्टल',
    status_outcome: 'स्थिती / निकाल',
    details_summary: 'तपशील सारांश',
    change_role: 'भूमिका बदला',
    role_citizen: 'नागरिक',
    role_authority: 'महानगरपालिका अधिकारी',
    role_admin: 'सिस्टम प्रशासक',
    update_pin: 'सुरक्षा पिन अपडेट करा',
    authority_pin: 'महानगरपालिका अधिकारी सुरक्षा पिन',
    admin_pin: 'सिस्टम प्रशासक सुरक्षा पिन',
    save_pin: 'नवीन पिन जतन करा',
    pin_saved_success: 'पिन यशस्वीरित्या अपडेट केला',
    ai_verification_enabled: 'एआय निवारण पडताळणी सक्षम',
  },
  ta: {
    app_title: 'கCrowdCivic AI',
    app_subtitle: 'AI சரிபார்ப்பு மற்றும் நகராட்சி தீர்வு அமைப்பு',
    citizen_portal: 'குடிமக்கள் போர்ட்டல்',
    authority_portal: 'நகராட்சி அதிகார போர்ட்டல்',
    admin_portal: 'கட்டளை மையம் & தணிக்கை',
    welcome: 'வரவேற்கிறோம்',
    report_issue: 'புகார் அளிக்கவும்',
    my_issues: 'என் அறிக்கைகள்',
    public_feed: 'பொது ஊட்டம்',
    leaderboard: 'முன்னணிப் பலகை',
    ai_agent: 'AI குடிமக்கள் உதவி',
    audit_logs: 'தணிக்கைப் பதிவுகள்',
    analytics: 'பகுப்பாய்வு',
    logout: 'வெளியேறு',
    signOut: 'வெளியேறு',
    sign_in: 'உள்நுழைக',
    sign_up: 'கணக்கை உருவாக்கு',
    status_pending: 'சரிபார்ப்பு நிலுவையில் உள்ளது',
    status_verified: 'AI சரிபார்க்கப்பட்டது',
    status_in_progress: 'செயல்பாட்டில் உள்ளது',
    status_resolved: 'தீர்வு காணப்பட்டது',
    status_rejected: 'நிராகரிக்கப்பட்டது',
    severity_high: 'அதிக தீவிரம்',
    severity_medium: 'மிதமான தீவிரம்',
    severity_low: 'குறைந்த தீவிரம்',
    category_roads: 'சாலைகள் மற்றும் உள்கட்டமைப்பு',
    category_sanitation: 'சுகாதாரம் மற்றும் கழிவு',
    category_water: 'குடிநீர் விநியோகம்',
    category_electricity: 'மின்சாரம் மற்றும் விளக்குகள்',
    category_other: 'இதர நகராட்சி பிரச்சனை',
    submit: 'அறிக்கையைச் சமர்ப்பி',
    cancel: 'ரத்து செய்',
    search_placeholder: 'பிரச்சனைகளைத் தேடுங்கள்...',
    location: 'இருப்பிடம்',
    upvote: 'ஆதரி',
    verify_resolution: 'தீர்வைச் சரிபார்',
    verify_ai_photo: 'லைவ் AI புகைப்படத்துடன் சரிபார்',
    confidence_score: 'AI நம்பிக்கை மதிப்பெண்',
    view_details: 'விவரங்களைப் பார்',
    export_data: 'தரவை ஏற்றுமதி செய்',
    total_issues: 'மொத்த புகார்கள்',
    resolved_issues: 'வெற்றிகரமாக தீர்க்கப்பட்டவை',
    ai_verified_pct: 'AI சரிபார்ப்பு விகிதம்',
    avg_resolution_time: 'சராசரி தீர்வு நேரம்',
    incidents_command: 'சம்பவங்கள் & தீர்வு கட்டளை',
    authority_subtitle: 'குடிமக்கள் அறிக்கைகளை ஆய்வு செய்து 30 வினாடி நேரலை வீடியோ ஆதாரம் மற்றும் AI இடவியல் சரிபார்ப்புடன் சிக்கல்களைத் தீர்க்கவும்.',
    refresh_incidents: 'புதுப்பிக்குக',
    total_reports: 'மொத்த அறிக்கைகள்',
    pending_review: 'ஆய்வு நிலுவையில் உள்ளது',
    ai_resolved: 'AI தீர்த்தது',
    audit_failed: 'தணிக்கை தோல்வி',
    search_authority_placeholder: 'டிக்கெட் ஐடி, தலைப்பு, இடம் தேடுக...',
    inspect_resolve: 'ஆய்வு செய்து தீர்க்கவும்',
    record_live_video: '30 வினாடி நேரலை வீடியோ பதிவு செய்',
    recording_video: 'நேரலை வீடியோ பதிவாகிறது...',
    submit_ai_verification: 'AI சரிபார்ப்பிற்குச் சமர்ப்பி',
    verifying_resolution: 'AI இடவியல் சரிபார்ப்பு நடைபெறுகிறது...',
    verification_passed: 'தீர்வு சரிபார்க்கப்பட்டு ஒப்புதல் பெறப்பட்டது',
    verification_failed: 'AI தீர்வு தணிக்கை தோல்வி',
    citizen_complaint_details: 'குடிமகன் புகார் விவரங்கள்',
    ticket_id: 'டிக்கெட் ஐடி',
    category: 'வகை',
    issue_type: 'பிரச்சனை வகை',
    severity: 'தீவிரம்',
    department: 'துறை',
    reported_by: 'புகாரளித்தவர்',
    location_address: 'இருப்பிடம் / முகவரி',
    community_votes: 'சமூக சரிபார்ப்பு வாக்குகள்',
    admin_title: 'நகராட்சி அமைப்பு கட்டளை மையம்',
    admin_subtitle: 'முழு அமைப்பு கண்காணிப்பு, பாதுகாப்பு தணிக்கைப் பதிவுகள் மற்றும் பயனர் நிர்வாகம்.',
    tab_audit: 'பாதுகாப்பு தணிக்கைப் பதிவுகள்',
    tab_users: 'பதிவுசெய்த பயனர்கள் & பங்குகள்',
    tab_config: 'அமைப்பு பாதுகாப்பு & பின் அமைப்பு',
    tab_issues: 'சர்ச்சைக்குரிய அறிக்கைகள் நிர்வாகம்',
    total_audit_events: 'மொத்த தணிக்கை நிகழ்வுகள்',
    denied_access_attempts: 'மறுக்கப்பட்ட அணுகல் முயற்சிகள்',
    registered_users_count: 'பதிவுசெய்த பயனர்கள்',
    disputed_reports_count: 'சர்ச்சைக்குரிய அறிக்கைகள்',
    search_logs_placeholder: 'தணிக்கைப் பதிவுகள், மின்னஞ்சல் தேடுக...',
    filter_all: 'எல்லாப் பதிவுகளும்',
    filter_denied: 'மறுக்கப்பட்டவை',
    filter_pin: 'பின் செயல்பாடு',
    filter_login: 'உள்நுழைவு',
    event_timestamp: 'நேரமுத்திரை',
    action_event: 'செயல் நிகழ்வு',
    user_email: 'பயனர் மின்னஞ்சல்',
    portal_accessed: 'போர்ட்டல்',
    status_outcome: 'நிலை / முடிவு',
    details_summary: 'விவரச் சுருக்கம்',
    change_role: 'பங்கை மாற்று',
    role_citizen: 'குடிமகன்',
    role_authority: 'நகராட்சி அதிகாரி',
    role_admin: 'அமைப்பு நிர்வாகி',
    update_pin: 'பாதுகாப்பு பின்னைப் புதுப்பி',
    authority_pin: 'நகராட்சி அதிகாரி பாதுகாப்பு பின்',
    admin_pin: 'அமைப்பு நிர்வாகி பாதுகாப்பு பின்',
    save_pin: 'புதிய பின்னைச் சேமி',
    pin_saved_success: 'பின் வெற்றிகரமாகப் புதுப்பிக்கப்பட்டது',
    ai_verification_enabled: 'AI தீர்வு சரிபார்ப்பு இயக்கப்பட்டது',
  },
  te: {
    app_title: 'CrowdCivic AI',
    app_subtitle: 'AI సరిచూసే వ్యవస్థ & మునిసిపల్ పరిష్కార వ్యవస్థ',
    citizen_portal: 'పౌరుల పోర్టల్',
    authority_portal: 'మునిసిపల్ అధికారి పోర్టల్',
    admin_portal: 'కమాండ్ సెంటర్ & ఆడిట్',
    welcome: 'స్వాగతం',
    report_issue: 'సమస్యను నివేదించండి',
    my_issues: 'నా నివేదికలు',
    public_feed: 'పబ్లిక్ ఫీడ్',
    leaderboard: 'లీడర్‌బోర్డ్',
    ai_agent: 'AI పౌర సహాయకుడు',
    audit_logs: 'ఆడిట్ లాగ్స్',
    analytics: 'విశ్లేషణ',
    logout: 'లాగ్ అవుట్',
    signOut: 'సైన్ అవుట్',
    sign_in: 'సైన్ ఇన్ చేయండి',
    sign_up: 'ఖాతా తెరవండి',
    status_pending: 'సరిచూడడం పెండింగ్‌లో ఉంది',
    status_verified: 'AI సరిచూసింది',
    status_in_progress: 'పురోగతిలో ఉంది',
    status_resolved: 'పరిష్కరించబడింది',
    status_rejected: 'తిరస్కరించబడింది',
    severity_high: 'అధిక తీవ్రత',
    severity_medium: 'మధ్యస్థ తీవ్రత',
    severity_low: 'తక్కువ తీవ్రత',
    category_roads: 'రోడ్లు & మౌలిక సదుపాయాలు',
    category_sanitation: 'పరిశుభ్రత & చెత్త',
    category_water: 'నీటి సరఫరా',
    category_electricity: 'విద్యుత్ & లైటింగ్',
    category_other: 'ఇతర మునిసిపల్ సమస్య',
    submit: 'నివేదికను సమర్పించండి',
    cancel: 'రద్దు చేయండి',
    search_placeholder: 'సమస్యలను వెతకండి...',
    location: 'ప్రాంతం',
    upvote: 'మద్దతు ఇవ్వండి',
    verify_resolution: 'పరిష్కారాన్ని సరిచూడండి',
    verify_ai_photo: 'లైవ్ AI ఫోటోతో సరిచూడండి',
    confidence_score: 'AI విశ్వసనీయత స్కోరు',
    view_details: 'వివరాలు చూడండి',
    export_data: 'డేటా ఎగుమతి చేయండి',
    total_issues: 'మొత్తం నమోదు చేసిన సమస్యలు',
    resolved_issues: 'విజయవంతంగా పరిష్కరించబడినవి',
    ai_verified_pct: 'AI సరిచూసిన శాతం',
    avg_resolution_time: 'సగటు పరిష్కార సమయం',
    incidents_command: 'సంఘటనలు & పరిష్కార కమాండ్',
    authority_subtitle: 'పౌరుల నివేదికలను పరిశీలించి 30 సెకన్ల ప్రత్యక్ష వీడియో ఆధారం మరియు AI సరిచూసే వ్యవస్థతో సమస్యలను పరిష్కరించండి.',
    refresh_incidents: 'తాజాకరించండి',
    total_reports: 'మొత్తం నివేదికలు',
    pending_review: 'పరిశీలన పెండింగ్‌లో ఉంది',
    ai_resolved: 'AI పరిష్కరించింది',
    audit_failed: 'ఆడిట్ విఫలమైంది',
    search_authority_placeholder: 'టికెట్ ఐడీ, శీర్షిక, ప్రాంతం వెతకండి...',
    inspect_resolve: 'పరిశీలించి పరిష్కరించండి',
    record_live_video: '30 సెకన్ల ప్రత్యక్ష వీడియో రికార్డ్ చేయండి',
    recording_video: 'వీడియో రికార్డ్ అవుతోంది...',
    submit_ai_verification: 'AI సరిచూడటానికి సమర్పించండి',
    verifying_resolution: 'AI సరిచూసే ప్రక్రియ జరుగుతోంది...',
    verification_passed: 'పరిష్కారం సరిచూడబడింది మరియు ఆమోదించబడింది',
    verification_failed: 'AI పరిష్కార ఆడిట్ విఫలమైంది',
    citizen_complaint_details: 'పౌరుల ఫిర్యాదు వివరాలు',
    ticket_id: 'టికెట్ ఐడీ',
    category: 'వర్గం',
    issue_type: 'సమస్య రకం',
    severity: 'తీవ్రత',
    department: 'శాఖ',
    reported_by: 'నివేదించిన వారు',
    location_address: 'ప్రాంతం / చిరునామా',
    community_votes: 'సమాజ సరిచూసే ఓట్లు',
    admin_title: 'మునిసిపల్ వ్యవస్థ కమాండ్ సెంటర్',
    admin_subtitle: 'పూర్తి వ్యవస్థ పర్యవేక్షణ, భద్రతా ఆడిట్ లాగ్స్ మరియు వినియోగదారుల నిర్వహణ.',
    tab_audit: 'భద్రతా ఆడిట్ లాగ్స్',
    tab_users: 'నమోదిత వినియోగదారులు & పాత్రలు',
    tab_config: 'వ్యవస్థ భద్రత & పిన్ కాన్ఫిగరేషన్',
    tab_issues: 'వివాదాస్పద నివేదికల నిర్వహణ',
    total_audit_events: 'మొత్తం ఆడిట్ సంఘటనలు',
    denied_access_attempts: 'తిరస్కరించబడిన ప్రాప్యత ప్రయత్నాలు',
    registered_users_count: 'నమోదిత వినియోగదారులు',
    disputed_reports_count: 'వివాదాస్పద నివేదికలు',
    search_logs_placeholder: 'ఆడిట్ లాగ్స్, ఈమెయిల్ వెతకండి...',
    filter_all: 'అన్ని లాగ్స్',
    filter_denied: 'తిరస్కరించబడినవి',
    filter_pin: 'పిన్ కార్యకలాపాలు',
    filter_login: 'లాగిన్',
    event_timestamp: 'సమయ ముద్ర',
    action_event: 'చర్య రకం',
    user_email: 'వినియోగదారు ఈమెయిల్',
    portal_accessed: 'పోర్టల్',
    status_outcome: 'స్థితి / ఫలితం',
    details_summary: 'వివరాల సారాంశం',
    change_role: 'పాత్రను మార్చండి',
    role_citizen: 'పౌరుడు',
    role_authority: 'మునిసిపల్ అధికారి',
    role_admin: 'సిస్టమ్ అడ్మిన్',
    update_pin: 'భద్రతా పిన్ నవీకరించండి',
    authority_pin: 'మునిసిపల్ అధికారి భద్రతా పిన్',
    admin_pin: 'సిస్టమ్ అడ్మిన్ భద్రతా పిన్',
    save_pin: 'కొత్త పిన్ భద్రపరచండి',
    pin_saved_success: 'పిన్ విజయవంతంగా నవీకరించబడింది',
    ai_verification_enabled: 'AI పరిష్కార సరిచూసే వ్యవస్థ ప్రారంభించబడింది',
  },
  gu: {
    app_title: 'CrowdCivic AI',
    app_subtitle: 'એઆઈ ચકાસણી અને મ્યુનિસિપલ નિવારણ સિસ્ટમ',
    citizen_portal: 'નાગરિક પોર્ટલ',
    authority_portal: 'મ્યુનિસિપલ ઓથોરિટી પોર્ટલ',
    admin_portal: 'કમાન્ડ સેન્ટર અને ઓડિટ',
    welcome: 'સ્વાગત છે',
    report_issue: 'સમસ્યા નોંધાવો',
    my_issues: 'મારા અહેવાલો',
    public_feed: 'જાહેર ફીડ',
    leaderboard: 'લીડરબોર્ડ',
    ai_agent: 'એઆઈ નાગરિક સહાયક',
    audit_logs: 'ઓડિટ લોગ',
    analytics: 'વિશ્લેષણ',
    logout: 'લોગ આઉટ',
    signOut: 'સાઇન આઉટ',
    sign_in: 'સાઇન ઇન કરો',
    sign_up: 'ખાતું બનાવો',
    status_pending: 'ચકાસણી બાકી',
    status_verified: 'એઆઈ ચકાસાયેલ',
    status_in_progress: 'પ્રગતિમાં',
    status_resolved: 'ઉકેલાયેલ',
    status_rejected: 'અસ્વીકૃત',
    severity_high: 'ઉચ્ચ ગંભીરતા',
    severity_medium: 'મધ્યમ ગંભીરતા',
    severity_low: 'ઓછી ગંભીરતા',
    category_roads: 'રસ્તાઓ અને માળખાકીય સુવિધાઓ',
    category_sanitation: 'સ્વચ્છતા અને કચરો',
    category_water: 'પાણી પુરવઠો',
    category_electricity: 'વીજળી અને લાઇટિંગ',
    category_other: 'અન્ય મ્યુનિસિપલ સમસ્યા',
    submit: 'અહેવાલ સબમિટ કરો',
    cancel: 'રદ કરો',
    search_placeholder: 'નાગરિક સમસ્યાઓ શોધો...',
    location: 'સ્થળ',
    upvote: 'ટેકો આપો',
    verify_resolution: 'ઉકેલની ચકાસણી કરો',
    verify_ai_photo: 'લાઇવ એઆઈ ફોટોથી ચકાસો',
    confidence_score: 'એઆઈ વિશ્વાસ સ્કોર',
    view_details: 'વિગતો જુઓ',
    export_data: 'ડેટા નિકાસ કરો',
    total_issues: 'કુલ નોંધાયેલ સમસ્યાઓ',
    resolved_issues: 'સફળતાપૂર્વક ઉકેલાયેલ',
    ai_verified_pct: 'એઆઈ ચકાસણી દર',
    avg_resolution_time: 'સરેરાશ ઉકેલ સમય',
    incidents_command: 'ઘટનાઓ અને નિવારણ કમાન્ડ',
    authority_subtitle: 'નાગરિક અહેવાલોની તપાસ કરો અને ૩૦-સેકન્ડ લાઇવ વિડિઓ પુરાવા અને એઆઈ ચકાસણી સાથે સમસ્યાઓનો ઉકેલ લાવો.',
    refresh_incidents: 'તાજું કરો',
    total_reports: 'કુલ અહેવાલો',
    pending_review: 'સમીક્ષા બાકી',
    ai_resolved: 'એઆઈ દ્વારા ઉકેલાયેલ',
    audit_failed: 'ઓડિટ નિષ્ફળ',
    search_authority_placeholder: 'ટિકિટ આઈડી, શીર્ષક, સ્થળ શોધો...',
    inspect_resolve: 'તપાસ કરો અને ઉકેલો',
    record_live_video: '૩૦ સેકન્ડ લાઇવ વિડિઓ રેકોર્ડ કરો',
    recording_video: 'લાઇવ વિડિઓ રેકોર્ડ થઈ રહ્યો છે...',
    submit_ai_verification: 'એઆઈ ચકાસણી માટે સબમિટ કરો',
    verifying_resolution: 'એઆઈ ચકાસણી પ્રક્રિયા ચાલુ છે...',
    verification_passed: 'ઉકેલ ચકાસાયેલ અને મંજૂર',
    verification_failed: 'એઆઈ ઉકેલ ઓડિટ નિષ્ફળ',
    citizen_complaint_details: 'નાગરિક ફરિયાદ વિગતો',
    ticket_id: 'ટિકિટ આઈડી',
    category: 'શ્રેણી',
    issue_type: 'સમસ્યાનો પ્રકાર',
    severity: 'ગંભીરતા',
    department: 'વિભાગ',
    reported_by: 'રિપોર્ટર',
    location_address: 'સ્થળ / સરનામું',
    community_votes: 'સમુદાય ચકાસણી વોટ',
    admin_title: 'મ્યુનિસિપલ સિસ્ટમ કમાન્ડ સેન્ટર',
    admin_subtitle: 'સંપૂર્ણ સિસ્ટમ મોનિટરિંગ, સુરક્ષા ઓડિટ લોગ અને વપરાશકર્તા સંચાલન.',
    tab_audit: 'સુરક્ષા ઓડિટ લોગ',
    tab_users: 'નોંધાયેલા વપરાશકર્તાઓ અને ભૂમિકાઓ',
    tab_config: 'સિસ્ટમ સુરક્ષા અને પિન સેટિંગ્સ',
    tab_issues: 'વિવાદાસ્પદ અહેવાલોનું સંચાલન',
    total_audit_events: 'કુલ ઓડિટ ઇવેન્ટ્સ',
    denied_access_attempts: 'અસ્વીકૃત પ્રવેશ પ્રયાસો',
    registered_users_count: 'નોંધાયેલા વપરાશકર્તાઓ',
    disputed_reports_count: 'વિવાદાસ્પદ અહેવાલો',
    search_logs_placeholder: 'ઓડિટ લોગ, ઇમેઇલ શોધો...',
    filter_all: 'બધા લોગ',
    filter_denied: 'અસ્વીકૃત',
    filter_pin: 'પિન પ્રવૃત્તિ',
    filter_login: 'લોગિન',
    event_timestamp: 'સમય છાપ',
    action_event: 'પ્રક્રિયા પ્રકાર',
    user_email: 'વપરાશકર્તા ઇમેઇલ',
    portal_accessed: 'પોર્ટલ',
    status_outcome: 'સ્થિતિ / પરિણામ',
    details_summary: 'વિગતોનો સારાંશ',
    change_role: 'ભૂમિકા બદલો',
    role_citizen: 'નાગરિક',
    role_authority: 'મ્યુનિસિપલ ઓથોરિટી',
    role_admin: 'સિસ્ટમ એડમિન',
    update_pin: 'સુરક્ષા પિન અપડેટ કરો',
    authority_pin: 'મ્યુનિસિપલ ઓથોરિટી સુરક્ષા પિન',
    admin_pin: 'સિસ્ટમ એડમિન સુરક્ષા પિન',
    save_pin: 'નવો પિન સાચવો',
    pin_saved_success: 'પિન સફળતાપૂર્વક અપડેટ થયો',
    ai_verification_enabled: 'એઆઈ ઉકેલ ચકાસણી સક્રિય',
  },
  bn: {
    app_title: 'CrowdCivic AI',
    app_subtitle: 'এআই যাচাইকরণ ও পৌর সমাধান ব্যবস্থা',
    citizen_portal: 'নাগরিক পোর্টাল',
    authority_portal: 'পৌর কর্তৃপক্ষ পোর্টাল',
    admin_portal: 'কমান্ড সেন্টার ও অডিট',
    welcome: 'স্বাগতম',
    report_issue: 'সমস্যা রিপোর্ট করুন',
    my_issues: 'আমার রিপোর্টসমূহ',
    public_feed: 'পাবলিক ফিড',
    leaderboard: 'লিডারবোর্ড',
    ai_agent: 'এআই নাগরিক সহকারী',
    audit_logs: 'অডিট লগ',
    analytics: 'বিশ্লেষণ',
    logout: 'লগ আউট',
    signOut: 'সাইন আউট',
    sign_in: 'সাইন ইন করুন',
    sign_up: 'একাউন্ট তৈরি করুন',
    status_pending: 'যাচাইকরণ বিচারাধীন',
    status_verified: 'এআই দ্বারা যাচাইকৃত',
    status_in_progress: 'প্রক্রিয়াধীন',
    status_resolved: 'সমাধান করা হয়েছে',
    status_rejected: 'বাতিল করা হয়েছে',
    severity_high: 'উচ্চ তীব্রতা',
    severity_medium: 'মাঝারি তীব্রতা',
    severity_low: 'কম তীব্রতা',
    category_roads: 'রাস্তা ও অবকাঠামো',
    category_sanitation: 'পরিচ্ছন্নতা ও বর্জ্য',
    category_water: 'পানি সরবরাহ',
    category_electricity: 'বিদ্যুৎ ও আলো',
    category_other: 'অন্যান্য পৌর সমস্যা',
    submit: 'রিপোর্ট জমা দিন',
    cancel: 'বাতিল করুন',
    search_placeholder: 'পৌর সমস্যা খুঁজুন...',
    location: 'অবস্থান',
    upvote: 'সমর্থন জানান',
    verify_resolution: 'সমাধান যাচাই করুন',
    verify_ai_photo: 'লাইভ এআই ফটো দিয়ে যাচাই করুন',
    confidence_score: 'এআই আত্মবিশ্বাসের স্কোর',
    view_details: 'বিস্তারিত দেখুন',
    export_data: 'ডেটা এক্সপোর্ট করুন',
    total_issues: 'মোট রিপোর্টকৃত সমস্যা',
    resolved_issues: 'সফলভাবে সমাধান করা হয়েছে',
    ai_verified_pct: 'এআই যাচাইকরণের হার',
    avg_resolution_time: 'গড় সমাধানের সময়',
    incidents_command: 'ঘটনা ও সমাধান কমান্ড',
    authority_subtitle: 'নাগরিক রিপোর্টসমূহ পর্যবেক্ষণ করুন এবং ৩০-সেকেন্ডের লাইভ ভিডিও প্রমাণ ও এআই যাচাইকরণের মাধ্যমে সমস্যার সমাধান করুন।',
    refresh_incidents: 'রিফ্রেশ করুন',
    total_reports: 'মোট রিপোর্ট',
    pending_review: 'পর্যালোচনা বিচারাধীন',
    ai_resolved: 'এআই দ্বারা সমাধানকৃত',
    audit_failed: 'অডিট ব্যর্থ',
    search_authority_placeholder: 'টিকিট আইডি, শিরোনাম, স্থান খুঁজুন...',
    inspect_resolve: 'পর্যবেক্ষণ ও সমাধান',
    record_live_video: '৩০ সেকেন্ডের লাইভ ভিডিও রেকর্ড করুন',
    recording_video: 'লাইভ ভিডিও রেকর্ড হচ্ছে...',
    submit_ai_verification: 'এআই যাচাইকরণের জন্য জমা দিন',
    verifying_resolution: 'এআই স্থানিক যাচাইকরণ চলছে...',
    verification_passed: 'সমাধান যাচাইকৃত এবং অনুমোদিত',
    verification_failed: 'এআই সমাধান অডিট ব্যর্থ',
    citizen_complaint_details: 'নাগরিক অভিযোগের বিবরণ',
    ticket_id: 'টিকিট আইডি',
    category: 'বিভাগ',
    issue_type: 'সমস্যার ধরন',
    severity: 'তীব্রতা',
    department: 'বিভাগ',
    reported_by: 'রিপোর্টার',
    location_address: 'অবস্থান / ঠিকানা',
    community_votes: 'কমিউনিটি যাচাইকরণ ভোট',
    admin_title: 'পৌর ব্যবস্থা কমান্ড সেন্টার',
    admin_subtitle: 'সম্পূর্ণ ব্যবস্থা পর্যবেক্ষণ, নিরাপত্তা অডিট লগ এবং ব্যবহারকারী পরিচালনা।',
    tab_audit: 'নিরাপত্তা অডিট লগ',
    tab_users: 'নিবন্ধিত ব্যবহারকারী ও ভূমিকা',
    tab_config: 'ব্যবস্থা নিরাপত্তা ও পিন কনফিগারেশন',
    tab_issues: 'বিরোধপূর্ণ রিপোর্ট পরিচালনা',
    total_audit_events: 'মোট অডিট ইভেন্ট',
    denied_access_attempts: 'প্রত্যাখ্যাত অ্যাক্সেস চেষ্টা',
    registered_users_count: 'নিবন্ধিত ব্যবহারকারী',
    disputed_reports_count: 'বিরোধপূর্ণ রিপোর্ট',
    search_logs_placeholder: 'অডিট লগ, ইমেইল খুঁজুন...',
    filter_all: 'সকল লগ',
    filter_denied: 'প্রত্যাখ্যাত',
    filter_pin: 'পিন কার্যক্রম',
    filter_login: 'লগইন',
    event_timestamp: 'সময়',
    action_event: 'কার্যক্রমের ধরন',
    user_email: 'ব্যবহারকারীর ইমেইল',
    portal_accessed: 'পোর্টাল',
    status_outcome: 'অবস্থা / ফলাফল',
    details_summary: 'বিস্তারিত সারসংক্ষেপ',
    change_role: 'ভূমিকা পরিবর্তন করুন',
    role_citizen: 'নাগরিক',
    role_authority: 'পৌর কর্তৃপক্ষ',
    role_admin: 'সিস্টেম অ্যাডমিন',
    update_pin: 'নিরাপত্তা পিন আপডেট করুন',
    authority_pin: 'পৌর কর্তৃপক্ষ নিরাপত্তা পিন',
    admin_pin: 'সিস্টেম অ্যাডমিন নিরাপত্তা পিন',
    save_pin: 'নতুন পিন সংরক্ষণ করুন',
    pin_saved_success: 'পিন সফলভাবে আপডেট করা হয়েছে',
    ai_verification_enabled: 'এআই সমাধান যাচাইকরণ সক্রিয়',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    const saved = localStorage.getItem('crowdcivic_lang') as LanguageCode;
    if (saved && TRANSLATIONS[saved]) {
      setLanguageState(saved);
    }

    const handleLangSync = () => {
      const current = localStorage.getItem('crowdcivic_lang') as LanguageCode;
      if (current && TRANSLATIONS[current]) {
        setLanguageState(current);
      }
    };

    window.addEventListener('storage', handleLangSync);
    window.addEventListener('crowdcivic_lang_changed', handleLangSync);

    return () => {
      window.removeEventListener('storage', handleLangSync);
      window.removeEventListener('crowdcivic_lang_changed', handleLangSync);
    };
  }, []);

  const setLanguage = (code: LanguageCode) => {
    setLanguageState(code);
    localStorage.setItem('crowdcivic_lang', code);
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new Event('crowdcivic_lang_changed'));
    }
  };

  const t = (key: string, fallback?: string): string => {
    if (TRANSLATIONS[language] && TRANSLATIONS[language][key]) {
      return TRANSLATIONS[language][key];
    }
    if (TRANSLATIONS['en'] && TRANSLATIONS['en'][key]) {
      return TRANSLATIONS['en'][key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export function LanguageSelector({ className = '' }: { className?: string }) {
  const { language, setLanguage } = useLanguage();
  return (
    <div className={`relative inline-block ${className}`}>
      <select
        value={language}
        onChange={(e) => setLanguage(e.target.value as LanguageCode)}
        className="bg-white/10 hover:bg-white/20 text-white text-xs font-medium px-3 py-1.5 rounded-lg border border-white/20 focus:outline-none focus:border-blue-400 cursor-pointer transition-all"
      >
        {LANGUAGES.map((lang) => (
          <option key={lang.code} value={lang.code} className="bg-slate-900 text-white">
            {lang.nativeName} ({lang.name})
          </option>
        ))}
      </select>
    </div>
  );
}
